version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: alerthive-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: alerthive
      POSTGRES_PASSWORD: alerthive
      POSTGRES_DB: alerthive
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
